name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Run Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Project Frontend
        run: npm ci && npm run build

      - name: Install Composer Dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          args: --optimize-autoloader

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r -x "node_modules/" -x ".github/" -x ".git/"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: deploy-package
          path: release.zip
    
  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   environment: Production
  #   needs: build

  #   steps:
  #     - uses: burnett01/rsync-deployments@6.0.0
  #       with:
  #         switches: -avzr --delete --exclude-from=".gitignore"
  #         remote_path: $REMOTE_PATH
  #         remote_host: ${{ secrets.REMOTE_HOST }}
  #         remote_user: ${{ secrets.REMOTE_USER }}
  #         remote_key: ${{ secrets.DEPLOY_KEY }}