name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Run Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Project Frontend
        run: npm ci && npm run build

      - name: Install Composer Dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
          php_version: "8.1"
          args: --optimize-autoloader

      - name: Deploy
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --exclude-from="exclude.txt"
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
